App: Area.hpp Area.cpp Character.hpp Character.cpp Entity.hpp Entity.cpp GameModel.cpp GameModel.hpp GameModelTest.cpp
	g++ -std=c++14 Area.hpp Area.cpp Character.hpp Character.cpp Entity.hpp Entity.cpp GameModel.hpp GameModel.cpp GameModelTest.cpp -o GameModel
